window.xiaoWuCourseIndex = [
  {
    "lessonId": "lesson-001",
    "order": 1,
    "title": "免許制度",
    "subject": "宅建業法",
    "chapter": "宅建業法の入口",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-001.js"
  },
  {
    "lessonId": "lesson-002",
    "order": 2,
    "title": "宅建士制度",
    "subject": "宅建業法",
    "chapter": "宅建業法の入口",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-002.js"
  },
  {
    "lessonId": "lesson-003",
    "order": 3,
    "title": "営業保証金",
    "subject": "宅建業法",
    "chapter": "開業前の安全装置",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-003.js"
  },
  {
    "lessonId": "lesson-004",
    "order": 4,
    "title": "保証協会",
    "subject": "宅建業法",
    "chapter": "開業前の安全装置",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-004.js"
  },
  {
    "lessonId": "lesson-005",
    "order": 5,
    "title": "民法不是靠背出来的",
    "subject": "権利関係",
    "chapter": "民法思维",
    "estimatedMinutes": 50,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-005.js"
  },
  {
    "lessonId": "lesson-006",
    "order": 6,
    "title": "重要事項説明",
    "subject": "宅建業法",
    "chapter": "契約前の説明",
    "estimatedMinutes": 35,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-006.js"
  },
  {
    "lessonId": "lesson-007",
    "order": 7,
    "title": "35条書面",
    "subject": "宅建業法",
    "chapter": "契約前の説明",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-007.js"
  },
  {
    "lessonId": "lesson-008",
    "order": 8,
    "title": "37条書面",
    "subject": "宅建業法",
    "chapter": "契約後の書面",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-008.js"
  },
  {
    "lessonId": "lesson-009",
    "order": 9,
    "title": "報酬",
    "subject": "宅建業法",
    "chapter": "お金のルール",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-009.js"
  },
  {
    "lessonId": "lesson-010",
    "order": 10,
    "title": "監督処分",
    "subject": "宅建業法",
    "chapter": "違反したとき",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-010.js"
  },
  {
    "lessonId": "lesson-011",
    "order": 11,
    "title": "業務上の規制",
    "subject": "宅建業法",
    "chapter": "営業中のルール",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-011.js"
  },
  {
    "lessonId": "lesson-012",
    "order": 12,
    "title": "宅建業法総合復習",
    "subject": "宅建業法",
    "chapter": "総合復習",
    "estimatedMinutes": 35,
    "difficulty": "复习",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-012.js"
  },
  {
    "lessonId": "lesson-013",
    "order": 13,
    "title": "制限行為能力者",
    "subject": "権利関係",
    "chapter": "民法の入口",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-013.js"
  },
  {
    "lessonId": "lesson-014",
    "order": 14,
    "title": "意思表示",
    "subject": "権利関係",
    "chapter": "契約の成立",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-014.js"
  },
  {
    "lessonId": "lesson-015",
    "order": 15,
    "title": "代理",
    "subject": "権利関係",
    "chapter": "人に頼む契約",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-015.js"
  },
  {
    "lessonId": "lesson-016",
    "order": 16,
    "title": "時効",
    "subject": "権利関係",
    "chapter": "時間で権利が動く",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-016.js"
  },
  {
    "lessonId": "lesson-017",
    "order": 17,
    "title": "債務不履行",
    "subject": "権利関係",
    "chapter": "約束を守れないとき",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-017.js"
  },
  {
    "lessonId": "lesson-018",
    "order": 18,
    "title": "契約解除",
    "subject": "権利関係",
    "chapter": "契約を終わらせる",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-018.js"
  },
  {
    "lessonId": "lesson-019",
    "order": 19,
    "title": "抵当権",
    "subject": "権利関係",
    "chapter": "担保の中心",
    "estimatedMinutes": 35,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-019.js"
  },
  {
    "lessonId": "lesson-020",
    "order": 20,
    "title": "連帯保証",
    "subject": "権利関係",
    "chapter": "保証人の重さ",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-020.js"
  },
  {
    "lessonId": "lesson-021",
    "order": 21,
    "title": "相続",
    "subject": "権利関係",
    "chapter": "人が亡くなった後",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-021.js"
  },
  {
    "lessonId": "lesson-022",
    "order": 22,
    "title": "借地借家法",
    "subject": "権利関係",
    "chapter": "借りる人を守る",
    "estimatedMinutes": 35,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-022.js"
  },
  {
    "lessonId": "lesson-023",
    "order": 23,
    "title": "区分所有法",
    "subject": "権利関係",
    "chapter": "マンションのルール",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-023.js"
  },
  {
    "lessonId": "lesson-024",
    "order": 24,
    "title": "不動産登記法",
    "subject": "権利関係",
    "chapter": "権利を見える化",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-024.js"
  },
  {
    "lessonId": "lesson-025",
    "order": 25,
    "title": "権利関係総合復習",
    "subject": "権利関係",
    "chapter": "総合復習",
    "estimatedMinutes": 35,
    "difficulty": "复习",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-025.js"
  },
  {
    "lessonId": "lesson-026",
    "order": 26,
    "title": "都市計画法",
    "subject": "法令上の制限",
    "chapter": "街づくりの入口",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-026.js"
  },
  {
    "lessonId": "lesson-027",
    "order": 27,
    "title": "開発許可",
    "subject": "法令上の制限",
    "chapter": "土地を大きく変える",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-027.js"
  },
  {
    "lessonId": "lesson-028",
    "order": 28,
    "title": "建築基準法",
    "subject": "法令上の制限",
    "chapter": "建物の基本ルール",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-028.js"
  },
  {
    "lessonId": "lesson-029",
    "order": 29,
    "title": "建ぺい率",
    "subject": "法令上の制限",
    "chapter": "土地に建てられる面積",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-029.js"
  },
  {
    "lessonId": "lesson-030",
    "order": 30,
    "title": "容積率",
    "subject": "法令上の制限",
    "chapter": "建物のボリューム",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-030.js"
  },
  {
    "lessonId": "lesson-031",
    "order": 31,
    "title": "用途地域",
    "subject": "法令上の制限",
    "chapter": "場所ごとの使い方",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-031.js"
  },
  {
    "lessonId": "lesson-032",
    "order": 32,
    "title": "農地法",
    "subject": "法令上の制限",
    "chapter": "農地を守る",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-032.js"
  },
  {
    "lessonId": "lesson-033",
    "order": 33,
    "title": "国土利用計画法",
    "subject": "法令上の制限",
    "chapter": "大きな土地取引",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-033.js"
  },
  {
    "lessonId": "lesson-034",
    "order": 34,
    "title": "土地区画整理法",
    "subject": "法令上の制限",
    "chapter": "街を作り直す",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-034.js"
  },
  {
    "lessonId": "lesson-035",
    "order": 35,
    "title": "法令上の制限総合復習",
    "subject": "法令上の制限",
    "chapter": "総合復習",
    "estimatedMinutes": 35,
    "difficulty": "复习",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-035.js"
  },
  {
    "lessonId": "lesson-036",
    "order": 36,
    "title": "固定資産税",
    "subject": "税・その他",
    "chapter": "持っている人の税金",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-036.js"
  },
  {
    "lessonId": "lesson-037",
    "order": 37,
    "title": "不動産取得税",
    "subject": "税・その他",
    "chapter": "取得したときの税金",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-037.js"
  },
  {
    "lessonId": "lesson-038",
    "order": 38,
    "title": "登録免許税",
    "subject": "税・その他",
    "chapter": "登記するときの税金",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★",
    "status": "available",
    "lessonFile": "course/lesson-038.js"
  },
  {
    "lessonId": "lesson-039",
    "order": 39,
    "title": "印紙税",
    "subject": "税・その他",
    "chapter": "契約書の税金",
    "estimatedMinutes": 20,
    "difficulty": "基础",
    "importance": "★★★",
    "status": "available",
    "lessonFile": "course/lesson-039.js"
  },
  {
    "lessonId": "lesson-040",
    "order": 40,
    "title": "地価公示",
    "subject": "税・その他",
    "chapter": "土地価格の目安",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★",
    "status": "available",
    "lessonFile": "course/lesson-040.js"
  },
  {
    "lessonId": "lesson-041",
    "order": 41,
    "title": "不動産鑑定評価",
    "subject": "税・その他",
    "chapter": "価格を判断する",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★",
    "status": "available",
    "lessonFile": "course/lesson-041.js"
  },
  {
    "lessonId": "lesson-042",
    "order": 42,
    "title": "住宅金融支援機構",
    "subject": "税・その他",
    "chapter": "住宅ローンの支援",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★",
    "status": "available",
    "lessonFile": "course/lesson-042.js"
  },
  {
    "lessonId": "lesson-043",
    "order": 43,
    "title": "税・その他総合復習",
    "subject": "税・その他",
    "chapter": "総合復習",
    "estimatedMinutes": 30,
    "difficulty": "复习",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-043.js"
  }
];
