window.xiaoWuCourseIndex = [
  {
    "lessonId": "lesson-001",
    "order": 1,
    "title": "免許制度",
    "subject": "宅建業法",
    "chapter": "宅建業法の入口",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-001.js"
  },
  {
    "lessonId": "lesson-002",
    "order": 2,
    "title": "宅建士制度",
    "subject": "宅建業法",
    "chapter": "宅建業法の入口",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-002.js"
  },
  {
    "lessonId": "lesson-003",
    "order": 3,
    "title": "営業保証金",
    "subject": "宅建業法",
    "chapter": "開業前の安全装置",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-003.js"
  },
  {
    "lessonId": "lesson-004",
    "order": 4,
    "title": "保証協会",
    "subject": "宅建業法",
    "chapter": "開業前の安全装置",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-004.js"
  },
  {
    "lessonId": "lesson-005",
    "order": 5,
    "title": "民法不是靠背出来的",
    "subject": "権利関係",
    "chapter": "民法思维",
    "estimatedMinutes": 50,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-005.js"
  },
  {
    "lessonId": "lesson-006",
    "order": 6,
    "title": "继承和共有，为什么一算就乱？",
    "subject": "権利関係",
    "chapter": "相続・共有",
    "estimatedMinutes": 60,
    "difficulty": "进阶",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-006.js"
  },
  {
    "lessonId": "lesson-007",
    "order": 7,
    "title": "为什么不法行為总觉得很乱？其实只要记住这5张图。",
    "subject": "権利関係",
    "chapter": "不法行為・相続入門",
    "estimatedMinutes": 60,
    "difficulty": "进阶",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-007.js"
  },
  {
    "lessonId": "lesson-008",
    "order": 8,
    "title": "契約不適合責任，为什么越学越绕？",
    "subject": "権利関係",
    "chapter": "契約不適合責任",
    "estimatedMinutes": 45,
    "difficulty": "进阶",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-008.js"
  },
  {
    "lessonId": "lesson-009",
    "order": 9,
    "title": "建物为什么不用追求满分？",
    "subject": "税・その他",
    "chapter": "建物",
    "estimatedMinutes": 40,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-009.js"
  },
  {
    "lessonId": "lesson-010",
    "order": 10,
    "title": "土地题为什么也不用死背？",
    "subject": "税・その他",
    "chapter": "土地",
    "estimatedMinutes": 40,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-010.js"
  },
  {
    "lessonId": "lesson-011",
    "order": 11,
    "title": "广告有没有骗人？景品表示法这样学就够了",
    "subject": "税・その他",
    "chapter": "景品表示法",
    "estimatedMinutes": 45,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-011.js"
  },
  {
    "lessonId": "lesson-012",
    "order": 12,
    "title": "住宅金融支援機構到底在支援谁？",
    "subject": "税・その他",
    "chapter": "住宅金融支援機構",
    "estimatedMinutes": 50,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-012.js"
  },
  {
    "lessonId": "lesson-013",
    "order": 13,
    "title": "不動産鑑定評価，为什么反而适合关键词拿分？",
    "subject": "税・その他",
    "chapter": "不動産鑑定評価基準",
    "estimatedMinutes": 45,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-013.js"
  },
  {
    "lessonId": "lesson-014",
    "order": 14,
    "title": "地価公示法，国家为什么每年公布土地价格？",
    "subject": "税・その他",
    "chapter": "地価公示法",
    "estimatedMinutes": 40,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-014.js"
  },
  {
    "lessonId": "lesson-015",
    "order": 15,
    "title": "贈与税，为什么只抓住宅取得資金就够了？",
    "subject": "税・その他",
    "chapter": "贈与税",
    "estimatedMinutes": 40,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-015.js"
  },
  {
    "lessonId": "lesson-016",
    "order": 16,
    "title": "登録免許税，什么时候缴、什么时候不缴？",
    "subject": "税・その他",
    "chapter": "登録免許税",
    "estimatedMinutes": 45,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-016.js"
  },
  {
    "lessonId": "lesson-017",
    "order": 17,
    "title": "印紙税，哪些文书要贴印纸？",
    "subject": "税・その他",
    "chapter": "印紙税",
    "estimatedMinutes": 45,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-017.js"
  },
  {
    "lessonId": "lesson-018",
    "order": 18,
    "title": "所得税，不要算税，只抓特例",
    "subject": "税・その他",
    "chapter": "所得税",
    "estimatedMinutes": 50,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-018.js"
  },
  {
    "lessonId": "lesson-019",
    "order": 19,
    "title": "地価公示法，流程记住就能拿分",
    "subject": "税・その他",
    "chapter": "地価公示法",
    "estimatedMinutes": 45,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-019.js"
  },
  {
    "lessonId": "lesson-020",
    "order": 20,
    "title": "不動産取得税，别背数字，先判断取得",
    "subject": "税・その他",
    "chapter": "不動産取得税",
    "estimatedMinutes": 45,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-020.js"
  },
  {
    "lessonId": "lesson-021",
    "order": 21,
    "title": "相続",
    "subject": "権利関係",
    "chapter": "人が亡くなった後",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-021.js"
  },
  {
    "lessonId": "lesson-022",
    "order": 22,
    "title": "借地借家法",
    "subject": "権利関係",
    "chapter": "借りる人を守る",
    "estimatedMinutes": 35,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-022.js"
  },
  {
    "lessonId": "lesson-023",
    "order": 23,
    "title": "区分所有法",
    "subject": "権利関係",
    "chapter": "マンションのルール",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-023.js"
  },
  {
    "lessonId": "lesson-024",
    "order": 24,
    "title": "不動産登記法",
    "subject": "権利関係",
    "chapter": "権利を見える化",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-024.js"
  },
  {
    "lessonId": "lesson-025",
    "order": 25,
    "title": "権利関係総合復習",
    "subject": "権利関係",
    "chapter": "総合復習",
    "estimatedMinutes": 35,
    "difficulty": "复习",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-025.js"
  },
  {
    "lessonId": "lesson-026",
    "order": 26,
    "title": "都市計画法",
    "subject": "法令上の制限",
    "chapter": "街づくりの入口",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-026.js"
  },
  {
    "lessonId": "lesson-027",
    "order": 27,
    "title": "開発許可",
    "subject": "法令上の制限",
    "chapter": "土地を大きく変える",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-027.js"
  },
  {
    "lessonId": "lesson-028",
    "order": 28,
    "title": "建築基準法",
    "subject": "法令上の制限",
    "chapter": "建物の基本ルール",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-028.js"
  },
  {
    "lessonId": "lesson-029",
    "order": 29,
    "title": "建ぺい率",
    "subject": "法令上の制限",
    "chapter": "土地に建てられる面積",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-029.js"
  },
  {
    "lessonId": "lesson-030",
    "order": 30,
    "title": "容積率",
    "subject": "法令上の制限",
    "chapter": "建物のボリューム",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-030.js"
  },
  {
    "lessonId": "lesson-031",
    "order": 31,
    "title": "用途地域",
    "subject": "法令上の制限",
    "chapter": "場所ごとの使い方",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-031.js"
  },
  {
    "lessonId": "lesson-032",
    "order": 32,
    "title": "農地法",
    "subject": "法令上の制限",
    "chapter": "農地を守る",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-032.js"
  },
  {
    "lessonId": "lesson-033",
    "order": 33,
    "title": "国土利用計画法",
    "subject": "法令上の制限",
    "chapter": "大きな土地取引",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-033.js"
  },
  {
    "lessonId": "lesson-034",
    "order": 34,
    "title": "土地区画整理法",
    "subject": "法令上の制限",
    "chapter": "街を作り直す",
    "estimatedMinutes": 30,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-034.js"
  },
  {
    "lessonId": "lesson-035",
    "order": 35,
    "title": "法令上の制限総合復習",
    "subject": "法令上の制限",
    "chapter": "総合復習",
    "estimatedMinutes": 35,
    "difficulty": "复习",
    "importance": "★★★★★",
    "status": "available",
    "lessonFile": "course/lesson-035.js"
  },
  {
    "lessonId": "lesson-036",
    "order": 36,
    "title": "固定資産税",
    "subject": "税・その他",
    "chapter": "持っている人の税金",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-036.js"
  },
  {
    "lessonId": "lesson-037",
    "order": 37,
    "title": "不動産取得税",
    "subject": "税・その他",
    "chapter": "取得したときの税金",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-037.js"
  },
  {
    "lessonId": "lesson-038",
    "order": 38,
    "title": "登録免許税",
    "subject": "税・その他",
    "chapter": "登記するときの税金",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★",
    "status": "available",
    "lessonFile": "course/lesson-038.js"
  },
  {
    "lessonId": "lesson-039",
    "order": 39,
    "title": "印紙税",
    "subject": "税・その他",
    "chapter": "契約書の税金",
    "estimatedMinutes": 20,
    "difficulty": "基础",
    "importance": "★★★",
    "status": "available",
    "lessonFile": "course/lesson-039.js"
  },
  {
    "lessonId": "lesson-040",
    "order": 40,
    "title": "地価公示",
    "subject": "税・その他",
    "chapter": "土地価格の目安",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★",
    "status": "available",
    "lessonFile": "course/lesson-040.js"
  },
  {
    "lessonId": "lesson-041",
    "order": 41,
    "title": "不動産鑑定評価",
    "subject": "税・その他",
    "chapter": "価格を判断する",
    "estimatedMinutes": 25,
    "difficulty": "标准",
    "importance": "★★★",
    "status": "available",
    "lessonFile": "course/lesson-041.js"
  },
  {
    "lessonId": "lesson-042",
    "order": 42,
    "title": "住宅金融支援機構",
    "subject": "税・その他",
    "chapter": "住宅ローンの支援",
    "estimatedMinutes": 25,
    "difficulty": "基础",
    "importance": "★★★",
    "status": "available",
    "lessonFile": "course/lesson-042.js"
  },
  {
    "lessonId": "lesson-043",
    "order": 43,
    "title": "税・その他総合復習",
    "subject": "税・その他",
    "chapter": "総合復習",
    "estimatedMinutes": 30,
    "difficulty": "复习",
    "importance": "★★★★",
    "status": "available",
    "lessonFile": "course/lesson-043.js"
  }
];
