window.xiaoWuQuizBank = [
  {
    id: "q-lesson013-001",
    lessonId: "lesson-013",
    category: "価格",
    title: "不動産鑑定評価",
    question: "不動産鑑定評価里的「一般的要因」最接近下面哪一种？",
    choices: ["某套房子的朝向", "时代、社会、经济等整体背景", "旁边是否有公园", "同一区域内某块土地的个性"],
    answer: 1,
    explanation: "🌸 小吴解析：一般的要因看的是时代、社会、经济、生活方式这类大背景。房子自己的朝向、公园、旁边环境，更接近個別要因。",
    relatedLesson: "lesson-013",
    relatedSection: "価格形成要因",
    difficulty: "basic"
  },
  {
    id: "q-lesson013-002",
    lessonId: "lesson-013",
    category: "価格",
    title: "不動産鑑定評価",
    question: "「最有効使用の原則」最适合怎么理解？",
    choices: ["现在房主最喜欢的用法", "土地最便宜的用法", "最能发挥价值的使用方式", "法律上禁止的最高收益用法"],
    answer: 2,
    explanation: "🌸 小吴解析：最有効使用就是这个不动产最能发挥价值的用法。站前土地不一定只按自住住宅想，也可能按商业楼等更能发挥价值的方式判断。",
    relatedLesson: "lesson-013",
    relatedSection: "最有効使用",
    difficulty: "basic"
  },
  {
    id: "q-lesson013-003",
    lessonId: "lesson-013",
    category: "価格",
    title: "不動産鑑定評価",
    question: "「特殊価格」的关键词是哪一个？",
    choices: ["条件満たす", "市場性を有しない", "早期売却", "限定"],
    answer: 1,
    explanation: "🌸 小吴解析：特殊価格的关键词是市場性なし。文化財指定建造物、宗教建築物等，不是普通市场买卖的感觉。",
    relatedLesson: "lesson-013",
    relatedSection: "四种价格",
    difficulty: "basic"
  },
  {
    id: "q-lesson013-004",
    lessonId: "lesson-013",
    category: "価格",
    title: "不動産鑑定評価",
    question: "原価法主要看什么？",
    choices: ["类似成交案例", "未来纯收益", "重新建造同样不动产要多少钱", "一期间收益除以利率"],
    answer: 2,
    explanation: "🌸 小吴解析：原価法看再調達原価，再进行減価修正。类似成交案例是取引事例比較法，未来收益是収益還元法。",
    relatedLesson: "lesson-013",
    relatedSection: "鑑定評価手法",
    difficulty: "basic"
  },
  {
    id: "q-lesson013-005",
    lessonId: "lesson-013",
    category: "価格",
    title: "不動産鑑定評価",
    question: "直接還元法和DCF法的关键词组合，正确的是哪一个？",
    choices: ["直接還元法＝複数期間、DCF法＝一期間", "直接還元法＝一期間、DCF法＝連続する複数期間", "两者都只看一期間", "两者都必须深入计算"],
    answer: 1,
    explanation: "🌸 小吴解析：宅建里不用深挖DCF计算。关键词抓住就好：直接還元法＝一期間，DCF法＝連続する複数の期間。",
    relatedLesson: "lesson-013",
    relatedSection: "直接還元法・DCF法",
    difficulty: "standard"
  },
  {
    id: "q-lesson014-001",
    lessonId: "lesson-014",
    category: "価格",
    title: "地価公示法",
    question: "地価公示的价格，最准确的理解是？",
    choices: ["必须按这个价格成交", "国家公布的参考价格、目安、指標", "市町村决定的税额", "卖主希望卖出的价格"],
    answer: 1,
    explanation: "🌸 小吴解析：地価公示不是强制成交价，而是土地交易、公共补偿等可以参考的价格。小7记住：参考、目安、指標。",
    relatedLesson: "lesson-014",
    relatedSection: "地価公示の目的",
    difficulty: "basic"
  },
  {
    id: "q-lesson014-002",
    lessonId: "lesson-014",
    category: "価格",
    title: "地価公示法",
    question: "地価公示法的主线负责人是谁？",
    choices: ["都道府県知事", "市町村長", "国土交通大臣", "宅建業者"],
    answer: 2,
    explanation: "🌸 小吴解析：这章看到知事要特别小心。主线是国土交通大臣和土地鑑定委員，不是都道府県知事。",
    relatedLesson: "lesson-014",
    relatedSection: "负责人",
    difficulty: "basic"
  },
  {
    id: "q-lesson014-003",
    lessonId: "lesson-014",
    category: "価格",
    title: "地価公示法",
    question: "標準地里的「標準」是什么意思？",
    choices: ["最贵", "环境特别优良", "通常、普通", "最适合开发"],
    answer: 2,
    explanation: "🌸 小吴解析：標準地不是最好土地。標準＝通常。考试很爱把通常改成優良，小7要立刻发现。",
    relatedLesson: "lesson-014",
    relatedSection: "標準地",
    difficulty: "basic"
  },
  {
    id: "q-lesson014-004",
    lessonId: "lesson-014",
    category: "価格",
    title: "地価公示法",
    question: "標準地的鑑定評価，原则上由几名以上不動産鑑定士进行？",
    choices: ["1名以上", "2名以上", "7名全员", "市町村長1名"],
    answer: 1,
    explanation: "🌸 小吴解析：至少2名以上不動産鑑定士。理由也很直观：避免一个人判断太主观。",
    relatedLesson: "lesson-014",
    relatedSection: "鑑定評価",
    difficulty: "basic"
  },
  {
    id: "q-lesson014-005",
    lessonId: "lesson-014",
    category: "価格",
    title: "地価公示法",
    question: "地価公示的正式公布在哪里？",
    choices: ["电视新闻", "房地产网站", "官報", "市町村公告栏"],
    answer: 2,
    explanation: "🌸 小吴解析：正式公布是官報。电视、新闻、网络只是后来转载或报道。",
    relatedLesson: "lesson-014",
    relatedSection: "官報",
    difficulty: "basic"
  },
  {
    id: "q-lesson015-001",
    lessonId: "lesson-015",
    category: "税法",
    title: "贈与税",
    question: "住宅取得資金贈与里的重点是赠与什么？",
    choices: ["房屋本身", "买房资金", "宅建士证", "土地登记簿"],
    answer: 1,
    explanation: "🌸 小吴解析：老师强调，不是送房子，是送买房的钱。政府希望长辈手里的钱流向住宅取得。",
    relatedLesson: "lesson-015",
    relatedSection: "住宅取得資金贈与",
    difficulty: "basic"
  },
  {
    id: "q-lesson015-002",
    lessonId: "lesson-015",
    category: "税法",
    title: "贈与税",
    question: "住宅取得資金非課税的感觉，最接近哪一个？",
    choices: ["真正免税", "以后一定补缴", "只是登记延后", "只适用于国外住宅"],
    answer: 0,
    explanation: "🌸 小吴解析：非課税就是真正不用缴。它和相続時精算課税不同，后者是以后继承时一起结算。",
    relatedLesson: "lesson-015",
    relatedSection: "非課税",
    difficulty: "basic"
  },
  {
    id: "q-lesson015-003",
    lessonId: "lesson-015",
    category: "税法",
    title: "贈与税",
    question: "相続時精算課税最适合怎么理解？",
    choices: ["完全免税", "现在先给，以后继承时结算", "只给陌生人用", "只适用于直接送房"],
    answer: 1,
    explanation: "🌸 小吴解析：小吴口诀：真正免税＝非課税；只是延后结算＝相続時精算課税。",
    relatedLesson: "lesson-015",
    relatedSection: "相続時精算課税",
    difficulty: "standard"
  },
  {
    id: "q-lesson015-004",
    lessonId: "lesson-015",
    category: "税法",
    title: "贈与税",
    question: "住宅取得資金贈与为什么限定日本国内住宅？",
    choices: ["因为政府想促进日本房地产", "因为国外房子更便宜", "因为国外房子不能登记", "因为赠与税只存在国外"],
    answer: 0,
    explanation: "🌸 小吴解析：这是一种政策优惠。国家想促进日本国内住宅取得，国外买房就不是这个政策目标。",
    relatedLesson: "lesson-015",
    relatedSection: "日本国内住宅",
    difficulty: "basic"
  },
  {
    id: "q-lesson015-005",
    lessonId: "lesson-015",
    category: "税法",
    title: "贈与税",
    question: "老师对贈与税这一课的学习建议是什么？",
    choices: ["深入税率计算", "只抓住宅取得資金高频点", "完全放弃", "只背同族公司"],
    answer: 1,
    explanation: "🌸 小吴解析：贈与税不要深入。宅建考试真正高频的是住宅取得資金贈与这一块。",
    relatedLesson: "lesson-015",
    relatedSection: "学习策略",
    difficulty: "basic"
  },
  {
    id: "q-lesson016-001",
    lessonId: "lesson-016",
    category: "税法",
    title: "登録免許税",
    question: "登録免許税什么时候产生？",
    choices: ["办理登记时", "签订媒介契约时", "收到广告传单时", "看房时"],
    answer: 0,
    explanation: "🌸 小吴解析：登録免許税就是办理登记时国家收的税。所有权保存、所有权移转、抵押权设定都要想到它。",
    relatedLesson: "lesson-016",
    relatedSection: "登録免許税",
    difficulty: "basic"
  },
  {
    id: "q-lesson016-002",
    lessonId: "lesson-016",
    category: "税法",
    title: "登録免許税",
    question: "表示登记原则上为什么免税？",
    choices: ["因为它是法定义务性质强", "因为金额太高", "因为买卖价很低", "因为只给公司优惠"],
    answer: 0,
    explanation: "🌸 小吴解析：表示登记是国家要求你做的基础登记，为了固定资产税等管理，所以原则不收登録免許税。",
    relatedLesson: "lesson-016",
    relatedSection: "表示登记",
    difficulty: "basic"
  },
  {
    id: "q-lesson016-003",
    lessonId: "lesson-016",
    category: "税法",
    title: "登録免許税",
    question: "登録免許税的课税标准，原则上看什么？",
    choices: ["成交价", "固定资产税评价额", "卖主希望价", "中介报价"],
    answer: 1,
    explanation: "🌸 小吴解析：考试最爱拿成交价骗人。登録免許税原则看固定資産税評価額。",
    relatedLesson: "lesson-016",
    relatedSection: "课税标准",
    difficulty: "basic"
  },
  {
    id: "q-lesson016-004",
    lessonId: "lesson-016",
    category: "税法",
    title: "登録免許税",
    question: "抵押权设定登记的课税标准看什么？",
    choices: ["房价", "土地面积", "债权金额", "中介费"],
    answer: 2,
    explanation: "🌸 小吴解析：老师举例：10亿大楼只借1000万，抵押权设定当然看1000万债权金额，不看10亿房价。",
    relatedLesson: "lesson-016",
    relatedSection: "抵押权设定",
    difficulty: "standard"
  },
  {
    id: "q-lesson016-005",
    lessonId: "lesson-016",
    category: "税法",
    title: "登録免許税",
    question: "夫妻共有住宅60㎡，判断住宅减税面积时怎么想？",
    choices: ["各自30㎡，不满足", "看整套60㎡", "只看丈夫持分", "只看登记顺序"],
    answer: 1,
    explanation: "🌸 小吴解析：老师强调，面积看整套住宅，不是按持分拆成30㎡、30㎡。",
    relatedLesson: "lesson-016",
    relatedSection: "共有住宅",
    difficulty: "standard"
  },
  {
    id: "q-lesson017-001",
    lessonId: "lesson-017",
    category: "税法",
    title: "印紙税",
    question: "印紙税首先要判断什么？",
    choices: ["税额表所有金额", "课税文书还是非课税文书", "宅建士人数", "贷款年数"],
    answer: 1,
    explanation: "🌸 小吴解析：印紙税不是先背税额。先判断这份文书要不要贴印纸，方向就对了。",
    relatedLesson: "lesson-017",
    relatedSection: "课税文书",
    difficulty: "basic"
  },
  {
    id: "q-lesson017-002",
    lessonId: "lesson-017",
    category: "税法",
    title: "印紙税",
    question: "土地租赁合同和建物租赁合同，哪一个是高频正确对比？",
    choices: ["土地租赁课税，建物租赁非课税", "土地租赁非课税，建物租赁课税", "两者都非课税", "两者都一定课税"],
    answer: 0,
    explanation: "🌸 小吴解析：土地賃貸借契約書要贴，建物賃貸借契約書不用贴。这个对比是印紙税高频陷阱。",
    relatedLesson: "lesson-017",
    relatedSection: "土地 vs 建物租赁",
    difficulty: "basic"
  },
  {
    id: "q-lesson017-003",
    lessonId: "lesson-017",
    category: "税法",
    title: "印紙税",
    question: "普通个人卖自己住房收到房款开收据，为什么可能不用贴印纸？",
    choices: ["金额太大", "不是营业行为", "买方是亲属", "房子有贷款"],
    answer: 1,
    explanation: "🌸 小吴解析：营业に関しない受取書不课税。普通个人卖自己的マイホーム，不是营业行为。",
    relatedLesson: "lesson-017",
    relatedSection: "营业无关收据",
    difficulty: "basic"
  },
  {
    id: "q-lesson017-004",
    lessonId: "lesson-017",
    category: "税法",
    title: "印紙税",
    question: "一个文书里同时写土地买卖5000万和建筑承包3000万，记载金额怎么处理？",
    choices: ["相加8000万", "取高者5000万", "取低者3000万", "一定无记载金额"],
    answer: 1,
    explanation: "🌸 小吴解析：买卖＋承包是不同性质，取金额较高者。全部都是买卖时才相加。",
    relatedLesson: "lesson-017",
    relatedSection: "多个合同",
    difficulty: "standard"
  },
  {
    id: "q-lesson017-005",
    lessonId: "lesson-017",
    category: "税法",
    title: "印紙税",
    question: "没有贴应贴印纸时，老师让先抓哪个考试结论？",
    choices: ["原则3倍过怠税", "永远无处罚", "只补原额即可", "自动免税"],
    answer: 0,
    explanation: "🌸 小吴解析：没贴印纸，原则上会有过怠税，核心先记3倍；主动申报会减轻。",
    relatedLesson: "lesson-017",
    relatedSection: "过怠税",
    difficulty: "basic"
  },
  {
    id: "q-lesson018-001",
    lessonId: "lesson-018",
    category: "税法",
    title: "所得税",
    question: "卖房所得税看的是哪一个？",
    choices: ["卖价全部", "利润，也就是所得", "广告价格", "贷款余额"],
    answer: 1,
    explanation: "🌸 小吴解析：卖房不是卖价全部课税。取得费、转让费用、特别扣除等扣掉后，真正赚到的才是所得。",
    relatedLesson: "lesson-018",
    relatedSection: "所得",
    difficulty: "basic"
  },
  {
    id: "q-lesson018-002",
    lessonId: "lesson-018",
    category: "税法",
    title: "所得税",
    question: "长期・短期让渡所得的判断，关键看哪一天？",
    choices: ["买入当天", "卖出当天", "让渡那一年的1月1日", "契约签署后第30天"],
    answer: 2,
    explanation: "🌸 小吴解析：不是单纯“卖出时满5年”。要看让渡那一年1月1日時点是否超过5年。",
    relatedLesson: "lesson-018",
    relatedSection: "长期・短期",
    difficulty: "standard"
  },
  {
    id: "q-lesson018-003",
    lessonId: "lesson-018",
    category: "税法",
    title: "所得税",
    question: "3000万特别扣除里的「3年多」指什么？",
    choices: ["住满3年才能卖", "搬出后到3年经过那一年的12月31日前仍可能适用", "3年内必须买新房", "每3年必须申报一次"],
    answer: 1,
    explanation: "🌸 小吴解析：老师用“3年ちょい”帮大家记。搬出去以后，到3年经过那一年的12月31日前仍可能适用。",
    relatedLesson: "lesson-018",
    relatedSection: "3000万特别扣除",
    difficulty: "standard"
  },
  {
    id: "q-lesson018-004",
    lessonId: "lesson-018",
    category: "税法",
    title: "所得税",
    question: "3000万特别扣除，卖给谁通常不能适用？",
    choices: ["真正第三人", "完全陌生的买主", "配偶者等自己人", "普通公司买主"],
    answer: 2,
    explanation: "🌸 小吴解析：不能卖给自己人。配偶者、直系血亲、同居亲属、同族公司等都要小心。",
    relatedLesson: "lesson-018",
    relatedSection: "亲属限制",
    difficulty: "basic"
  },
  {
    id: "q-lesson018-005",
    lessonId: "lesson-018",
    category: "税法",
    title: "所得税",
    question: "3000万特别扣除和轻减税率，可以一起用吗？",
    choices: ["可以", "绝对不可以", "只有卖给亲属可以", "只有海外住宅可以"],
    answer: 0,
    explanation: "🌸 小吴解析：3000万＋轻减可以。5000万＋轻减也可以。但3000万＋5000万这种扣除同士不可以。",
    relatedLesson: "lesson-018",
    relatedSection: "适用关系",
    difficulty: "standard"
  },
  {
    id: "q-lesson019-001",
    lessonId: "lesson-019",
    category: "価格",
    title: "地価公示法",
    question: "地価公示法的主线起点是谁？",
    choices: ["国土交通大臣", "都道府県知事", "市町村長", "宅建士"],
    answer: 0,
    explanation: "🌸 小吴解析：流程从国土交通大臣开始。国土交通大臣任命土地鑑定委員，并决定公示区域。",
    relatedLesson: "lesson-019",
    relatedSection: "流程",
    difficulty: "basic"
  },
  {
    id: "q-lesson019-002",
    lessonId: "lesson-019",
    category: "価格",
    title: "地価公示法",
    question: "地価公示的价格基准日是哪一天？",
    choices: ["3月1日", "4月1日", "1月1日", "公布当天"],
    answer: 2,
    explanation: "🌸 小吴解析：价格是1月1日時点。3月左右是公布，不是价格基准日。",
    relatedLesson: "lesson-019",
    relatedSection: "时间",
    difficulty: "basic"
  },
  {
    id: "q-lesson019-003",
    lessonId: "lesson-019",
    category: "価格",
    title: "地価公示法",
    question: "標準地可以有建筑物吗？",
    choices: ["不能，有建筑就不能选", "可以选，但评价时按建筑不存在", "只能选最高楼", "只能选国有地"],
    answer: 1,
    explanation: "🌸 小吴解析：可以选有建筑或权利的土地。关键是评价时当作建筑物、地上権等不存在，也就是更地评价。",
    relatedLesson: "lesson-019",
    relatedSection: "更地评价",
    difficulty: "standard"
  },
  {
    id: "q-lesson019-004",
    lessonId: "lesson-019",
    category: "価格",
    title: "地価公示法",
    question: "普通土地交易中，公示价格主要作为？",
    choices: ["强制成交价", "指標、目安", "罚金标准", "贷款额度上限"],
    answer: 1,
    explanation: "🌸 小吴解析：普通交易里是指標、目安，努力参考。公共补偿等场景才更像基準。",
    relatedLesson: "lesson-019",
    relatedSection: "指標和基準",
    difficulty: "standard"
  },
  {
    id: "q-lesson019-005",
    lessonId: "lesson-019",
    category: "価格",
    title: "地価公示法",
    question: "地価公示正式公布在哪里？",
    choices: ["官報", "电视", "房地产公司官网", "SNS"],
    answer: 0,
    explanation: "🌸 小吴解析：正式公布在官報。电视、网络是后来报道。",
    relatedLesson: "lesson-019",
    relatedSection: "官報",
    difficulty: "basic"
  },
  {
    id: "q-lesson020-001",
    lessonId: "lesson-020",
    category: "税法",
    title: "不動産取得税",
    question: "不動産取得税的纳税义务人是谁？",
    choices: ["卖方", "取得人", "中介公司", "市町村長"],
    answer: 1,
    explanation: "🌸 小吴解析：谁取得，谁纳税。买方、受赠人等取得房地产的人才是纳税义务人。",
    relatedLesson: "lesson-020",
    relatedSection: "纳税义务人",
    difficulty: "basic"
  },
  {
    id: "q-lesson020-002",
    lessonId: "lesson-020",
    category: "税法",
    title: "不動産取得税",
    question: "东京人买北海道的不动产，不動産取得税缴给哪里？",
    choices: ["东京", "北海道", "住所地市町村", "国税厅"],
    answer: 1,
    explanation: "🌸 小吴解析：不看住所地，看不动产所在地。北海道的不动产，就缴给北海道。",
    relatedLesson: "lesson-020",
    relatedSection: "所在地都道府県",
    difficulty: "basic"
  },
  {
    id: "q-lesson020-003",
    lessonId: "lesson-020",
    category: "税法",
    title: "不動産取得税",
    question: "不動産取得税的课税标准原则上是什么？",
    choices: ["成交价", "固定資産税評価額", "卖方报价", "贷款金额"],
    answer: 1,
    explanation: "🌸 小吴解析：又是成交价陷阱。不動産取得税的课税标准是固定資産税評価額。",
    relatedLesson: "lesson-020",
    relatedSection: "课税标准",
    difficulty: "basic"
  },
  {
    id: "q-lesson020-004",
    lessonId: "lesson-020",
    category: "税法",
    title: "不動産取得税",
    question: "商业大楼的土地，不動産取得税税率按什么理解？",
    choices: ["住宅外建筑所以4%", "土地所以3%", "一定免税", "按住所地决定"],
    answer: 1,
    explanation: "🌸 小吴解析：商业大楼本体是住宅外建筑，可能4%。但土地是土地，仍然3%。",
    relatedLesson: "lesson-020",
    relatedSection: "税率",
    difficulty: "standard"
  },
  {
    id: "q-lesson020-005",
    lessonId: "lesson-020",
    category: "税法",
    title: "不動産取得税",
    question: "宅地减半，减的是哪一个？",
    choices: ["税率", "课税标准", "题目数量", "登记人数"],
    answer: 1,
    explanation: "🌸 小吴解析：宅地是课税标准二分之一，不是税率二分之一。先把元の金額减半，再乘税率。",
    relatedLesson: "lesson-020",
    relatedSection: "宅地减半",
    difficulty: "standard"
  }
];
